version: "3.3"
services:
  go-vm:
    image: go-vm:latest
    restart: always
      environment:
        HOST: vcenter.domain.tld
        USERID: username
        PASSWORD: password
    ports:
      - "8080:8080"